using NSwag;

namespace Digdir.Domain.Dialogporten.WebApi.Common.Json;
public static class OpenApiPostProcessors
{
    public static void RemoveUnreferencedSchemas(OpenApiDocument doc)
    {
        // These schemas are generated by NSwag, but are not referenced by anything since
        // PaginatedListParametersProcessor change the types for ContinuationToken
        // and OrderBy.
        //
        // A generic approach appears to be difficult, as the generated names only
        // appear in Definitions root property, and not within Paths.
        var schemasToRemove = new[]
        {
            "ContinuationTokenSetOfSearchDialogQueryOrderDefinitionAndSearchDialogDto",
            "ContinuationTokenSetOfSearchDialogQueryOrderDefinitionAndSearchDialogDto2",
            "OrderSetOfSearchDialogQueryOrderDefinitionAndSearchDialogDto",
            "OrderSetOfSearchDialogQueryOrderDefinitionAndSearchDialogDto2",
            "OrderOfSearchDialogDto",
            "OrderOfSearchDialogDto2",
        };

        foreach (var schema in schemasToRemove)
        {
            if (doc.Definitions.ContainsKey(schema)) doc.Definitions.Remove(schema);
        }
    }
}
